//Initial Content Actions types
export const FETCH_INITIAL_CONTENT_REQUEST = 'FETCH_INITIAL_CONTENT_REQUEST';
export const FETCH_INITIAL_CONTENT_SUCCESS = 'FETCH_INITIAL_CONTENT_SUCCESS';
export const FETCH_INITIAL_CONTENT_FAILURE = 'FETCH_INITIAL_CONTENT_FAILURE';